# Generated by Django 5.1.6 on 2025-07-11 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=244, verbose_name='Назва наявності')),
            ],
        ),
        migrations.CreateModel(
            name='Services_and_Price_menu_list_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=244, verbose_name='Назва категорії')),
                ('img', models.FileField(upload_to='Services_and_Price_menu_list_item/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['id', 'Title'],
            },
        ),
        migrations.CreateModel(
            name='Services_and_Price_product_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=244, verbose_name='Назва товару')),
                ('price', models.CharField(max_length=244, verbose_name='Ціна')),
                ('img', models.FileField(upload_to='Services_and_Price_product_item/', verbose_name='Зображення')),
                ('Size', models.CharField(max_length=244, verbose_name='Розмір')),
                ('Product_code', models.CharField(max_length=244, verbose_name='Код товару')),
                ('Price_in_detail', models.CharField(max_length=244, verbose_name='Ціна детально')),
                ('Characteristics', models.TextField(verbose_name='Характеристики')),
                ('Description', models.TextField(verbose_name='Опис товару')),
                ('Name_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.services_and_price_menu_list_item', verbose_name='Вибрати пункт в меню')),
                ('Product_availability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.availability', verbose_name='Наявність товару')),
            ],
            options={
                'verbose_name': 'Каталог товару',
                'verbose_name_plural': 'Каталог товару',
                'ordering': ['id', 'Title'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Зображення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mysite.services_and_price_product_item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Зображення товару',
                'verbose_name_plural': 'Зображення товарів',
            },
        ),
    ]
