# Generated by Django 5.1.6 on 2025-07-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name': 'Наявність', 'verbose_name_plural': 'Наявність'},
        ),
        migrations.RenameField(
            model_name='services_and_price_product_item',
            old_name='Price_in_detail',
            new_name='Price_in_detail_evro',
        ),
        migrations.AddField(
            model_name='services_and_price_product_item',
            name='Price_in_detail_o',
            field=models.CharField(default=1, max_length=244, verbose_name='Ціна детально'),
            preserve_default=False,
        ),
    ]
