# Generated by Django 5.1.6 on 2025-12-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services_and_price_product_item',
            name='priority',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Пріоритет'),
        ),
        migrations.AlterField(
            model_name='services_and_price_product_item',
            name='Price_in_detail_evro',
            field=models.CharField(max_length=244, verbose_name='Ціна детально (евро)'),
        ),
    ]
