"""
Django settings for Granit project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#x^9du2se+f7qzz8@ldia3x+g2da7(2iw88f1-kzp*hp^wlh)!'

# SECURITY WARNING: don't run with debug turned on in production!
debug_file_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'DEBUG.txt')
# Перевіряємо наявність файлу DEBUG.txt і встановлюємо значення DEBUG
if os.path.exists(debug_file_path):
    DEBUG = True
else:
    DEBUG = False

ALLOWED_HOSTS = ['192.168.0.183', 'localhost', '127.0.0.1', '192.168.0.107', 'garant-bud.pl', 'www.garant-bud.pl', '192.168.0.47']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mysite.apps.MysiteConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Granit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Granit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

debug_file_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'DEBUG.txt')
# Перевіряємо наявність файлу DEBUG.txt і встановлюємо значення DEBUG

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'test.db',
#     }
# }

if os.path.exists(debug_file_path):
    DATABASES = {
        'default': {
            # 'ENGINE': 'mysql.connector.django',
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'Granit',
            'USER': 'jf94XM5pH2GaV88DGkzk8U7nr6C77fGj',
            'PASSWORD': '263457MKp5MkPXtVzxCFx2nnUNy9hb75',
            'HOST': '10.8.0.1',
            'PORT': '3306'
        }
    }
else:
    DATABASES = {
        'default': {
            # 'ENGINE': 'mysql.connector.django',
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'Granit',
            'USER': 'jf94XM5pH2GaV88DGkzk8U7nr6C77fGj',
            'PASSWORD': '263457MKp5MkPXtVzxCFx2nnUNy9hb75',
            'HOST': '192.168.0.19',
            'PORT': '3306'
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'uk'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Папка, куда будут сохраняться загруженные пользователем медиа-файлы
MEDIA_ROOT = BASE_DIR / 'media'
# URL, за яким статичні файли будуть доступні в браузері
STATIC_URL = '/static/'

# Директорія, куди Django збирає всі статичні файли під час виконання `collectstatic`
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Додаткові директорії, де можуть розташовуватися статичні файли
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',  # Глобальна директорія для статичних файлів проекту
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} - {levelname} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'errors.log',
            'formatter': 'verbose',
        },
        'custom_file': {
            'level': 'ERROR',
            'class': 'mysite.logging_handlers.CustomFileHandler',  # Змінено на правильний шлях
            'filename': 'errors.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['custom_file'],  # Використовуємо кастомний хендлер
            'level': 'ERROR',
            'propagate': True,
        },
    },
}